#!/bin/sh

TESTRUNNER="rspec spec/*.rb"
WATCHED="*.rb spec/*.rb"
EXITCODE=0

if which >/dev/null inotifywait; then
    $TESTRUNNER
    while true; do
        inotifywait -q -r -e modify,move,create,delete,attrib --exclude "\.\#" $WATCHED
        $TESTRUNNER
    done
else
    echo "Not implemented"
    EXITCODE=255
fi

exit $EXITCODE
